apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilesam-deployment
  labels:
    app: mobilesam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobilesam
  template:
    metadata:
      labels:
        app: mobilesam
    spec:
      containers:
        - name: mobilesam
          image: gcr.io/PROJECT_ID/mobilesam:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mobilesam-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: mobilesam
